[tool.poetry]
name = "tournament_games_project"
version = "0.1.0"
description = ""
authors = ["Catalin Suceveanu"]

[tool.poetry.dependencies]
python = "3.10.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
